language: bash
services: docker

env:
  - VERSION=latest

before_script:
  - env | sort
  - image="docker-mysql-base:$VERSION"

script:
  - travis_retry docker build -t "$image" .
  - ./test/run.sh "$image"

after_script:
  - docker images

